### ISSUE TITLE
`Unable to find libclang`

### ISSUE THREAD

**Issue by larseggert** [psumbera/solaris-rust#1]
I get
```
Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
```
when I try to build something. See for example https://github.com/mozilla/mtu/actions/runs/11893820949/job/33139646930?pr=29#step:7:1555

**Comment by larseggert** [comment]
This is probably because the crate needs `bindgen`.

**Comment by psumbera** [comment]
I think you need to have installed libclang. Please try `pkg install userland` (this should install all relevant build packages including the one with libclang).

**Comment by larseggert** [comment]
I guess I still need to set `LIBCLANG_PATH` to something as well?

Is it possible to just install `libclang`? `userland` takes a **long** time...

**Comment by psumbera** [comment]
Yes. `pkg install clang-libs` (https://github.com/oracle/solaris-userland/blob/923dbf87ecc01b5f8b6ea0397e81ca850bfc12a6/components/llvm/clang-libs.p5m#L28)

You might need also `pkg install cmake gcc ninja pkg-config`.

**Comment by larseggert** [comment]
Where does `pkg` install into?

**Comment by psumbera** [comment]
It installs into /. Should be here: https://github.com/oracle/solaris-userland/blob/923dbf87ecc01b5f8b6ea0397e81ca850bfc12a6/components/llvm/clang-libs.p5m#L46C29-L46C43

BTW. What are you doing? Are you trying to build Firefox on Solaris? On which system? Latest SRU as it's available on cfarm? or Solaris CBE release?

**Comment by larseggert** [comment]
No, not Firefox. We're about to add the `mtu` crate as a dependency to the QUIC stack, and I want to see if I can get it to work on Solaris.
